#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Mon Oct 20 14:22:01 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade




class Ventana4(wx.Frame):
    def __init__(self, parent, informacion="", subtotal1=0, informacion2="", subtotal2=0):
        # begin wxGlade: Ventana4.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)

        self.SetSize((466, 570))
        self.SetTitle("Ticket")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("./logo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 196, 207))
        self.panel_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        
        #Variables de instancia de la Ventana4
        self.infoTaquilla = informacion
        self.infoDulceria = informacion2
        self.subtotalTaquilla = subtotal1
        self.subtotalDulceria = subtotal2
        self.total=self.subtotalTaquilla+self.subtotalDulceria

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("G:\\19-novcine\\cineplus\\taquilla.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_3.SetMinSize((120, 30))
        label_3.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./taquilla.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_RIGHT, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetMinSize((384, 30))
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_1.Add(label_1, 0, wx.EXPAND, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoTaquilla}", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTaquilla.SetMinSize((100, 100))
        lbTaquilla.SetBackgroundColour(wx.Colour(255, 233, 238))
        sizer_1.Add(lbTaquilla, 0, wx.EXPAND, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal: ${self.subtotalTaquilla}")
        lbSubtotalTaquilla.SetForegroundColour(wx.Colour(14, 5, 116))
        lbSubtotalTaquilla.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_1.Add(lbSubtotalTaquilla, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"DULCERÍA", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetMinSize((384, 30))
        label_2.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_1.Add(label_2, 0, wx.EXPAND, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoDulceria}", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbDulceria.SetMinSize((100, 100))
        lbDulceria.SetBackgroundColour(wx.Colour(255, 233, 238))
        sizer_1.Add(lbDulceria, 0, wx.EXPAND, 0)

        lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal: ${self.subtotalDulceria}")
        lbSubtotalDulceria.SetForegroundColour(wx.Colour(14, 5, 116))
        lbSubtotalDulceria.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_1.Add(lbSubtotalDulceria, 0, 0, 0)

        lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"Total: ${self.total}", style=wx.ALIGN_RIGHT)
        lbTotal.SetForegroundColour(wx.Colour(194, 0, 0))
        lbTotal.SetFont(wx.Font(24, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_1.Add(lbTotal, 0, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar ")
        self.btnCancelar.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        self.btnCancelar.SetBitmap(wx.Bitmap("./cancelar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.btnCancelar, 0, 0, 0)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar")
        self.btnFinalizar.SetMinSize((175, 54))
        self.btnFinalizar.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        self.btnFinalizar.SetBitmap(wx.Bitmap("./bien.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.btnFinalizar, 0, wx.ALIGN_RIGHT, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        pregunta = wx.MessageDialog(self,"El programa se cerrará.\n¿Desea salir?","Confirmar salida",style=wx.YES_NO | wx.ICON_QUESTION)

        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            wx.Exit()        
        event.Skip()

    def finalizarVenta(self, event):  # wxGlade: Ventana4.<event_handler>
        wx.MessageBox(f"Total a Pagar ${self.total}", "Venta Finalizada", wx.OK | wx.ICON_INFORMATION)
        v2 = Ventana2(self)
        v2.Show()
        self.Hide() 

        event.Skip()

# end of class Ventana4
class Ventana3(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0):
        # begin wxGlade: Ventana3.__init__
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((920, 670))
        self.SetTitle(u"Dulcería")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("./logo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(156, 186, 69))
        self.panel_1.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        
        #Variables de Instancia Ventana3   
        self.infoDulceria=""
        self.subtotalDulceria=0
        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./dulceria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Dulcería")
        label_1.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_1, 0, 0, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./dulceria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_7 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboB.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_7.Add(self.spComboB, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Básico $75")
        label_2.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_8.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas ch\nRefresco ch")
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_8.Add(label_3, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("combo1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(bitmap_3, 0, 0, 0)

        grid_sizer_9 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_9.Add(self.spComboC, 0, 0, 0)

        grid_sizer_10 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $130")
        label_4.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_10.Add(label_4, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Plomitas Md")
        grid_sizer_10.Add(label_7, 0, 0, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_9.Add(bitmap_7, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_3.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_11.Add(self.spComboF, 0, 0, 0)

        grid_sizer_12 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $200")
        label_5.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_12.Add(label_5, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas G")
        grid_sizer_12.Add(label_6, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo3.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(bitmap_4, 0, 0, 0)

        grid_sizer_3.Add((0, 0), 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_13 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomita.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_13.Add(bitmap_5, 0, 0, 0)

        grid_sizer_14 = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_13.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_8.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_14.Add(label_8, 0, 0, 0)

        grid_sizer_15 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_14.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_15.Add(self.spPalomitasCh, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        grid_sizer_15.Add(label_9, 0, 0, 0)

        grid_sizer_16 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_14.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_16.Add(self.spPalomitasMd, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas")
        grid_sizer_16.Add(label_10, 0, 0, 0)

        grid_sizer_17 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_14.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_17.Add(self.spPalomitasG, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        grid_sizer_17.Add(label_11, 0, 0, 0)

        grid_sizer_18 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./refrescos.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_18.Add(bitmap_6, 0, 0, 0)

        grid_sizer_19 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_18.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        label_12.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_19.Add(label_12, 0, 0, 0)

        grid_sizer_21 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_19.Add(grid_sizer_21, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        label_13.SetMinSize((100, 19))
        grid_sizer_21.Add(label_13, 0, 0, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_14.SetMinSize((70, 19))
        grid_sizer_21.Add(label_14, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_15.SetMinSize((100, 19))
        grid_sizer_21.Add(label_15, 0, 0, 0)

        grid_sizer_20 = wx.FlexGridSizer(1, 4, 0, 0)
        grid_sizer_19.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["CHICO", "MEDIANO", "GRANDE"], style=wx.CB_DROPDOWN)
        grid_sizer_20.Add(self.cmbTamano, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["COCA COLA", "SPRITE", "MANZANA"], style=wx.CB_DROPDOWN)
        grid_sizer_20.Add(self.cmbSabor, 0, 0, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_20.Add(self.spCantidad, 0, 0, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        grid_sizer_20.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_22 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Agregados:")
        label_16.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_22.Add(label_16, 0, 0, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "...")
        self.lbProductosAgregados.SetMinSize((130, 100))
        grid_sizer_22.Add(self.lbProductosAgregados, 0, 0, 0)

        grid_sizer_23 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_23, 1, wx.EXPAND, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Subtotal Dulcería:")
        label_18.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_23.Add(label_18, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        self.lbSubtotal.SetForegroundColour(wx.Colour(189, 0, 0))
        self.lbSubtotal.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_23.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((160, 60))
        self.btnLimpiar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnLimpiar.SetBitmap(wx.Bitmap("./limpiar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(self.btnLimpiar, 0, 0, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((160, 60))
        self.btnSiguiente.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnSiguiente.SetBitmap(wx.Bitmap("./siguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(self.btnSiguiente, 0, wx.ALIGN_RIGHT, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboCuates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"\n{numero} Combos Basicos"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularComboCuates(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboC.GetValue())
        subtotalcombo=numero*130
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"\n{numero} Combos Cuates"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularComboFamiliar(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spComboF.GetValue())
        subtotalcombo=numero*200
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"\n{numero} Combos Familiares"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularPalomitasCh(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasCh.GetValue())
        subtotalcombo=numero*30
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"\n{numero} Palomitas Ch"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularPalomitasMd(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasMd.GetValue())
        subtotalcombo=numero*50
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"\n{numero} Palomitas Md"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()
    def calcularPalomitasG(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spPalomitasG.GetValue())
        subtotalcombo=numero*70
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"\n{numero} Palomitas G"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def agregarRefresco(self, event):  # wxGlade: Ventana3.<event_handler>
        numero=int(self.spCantidad.GetValue())
        tamanyo=self.cmbTamano.GetValue()
        sabor=self.cmbSabor.GetValue()

        if tamanyo == "CHICO":
            subtotalrefresco=numero*25
        elif tamanyo == "MEDIANO":
            subtotalrefresco=numero*40
        elif tamanyo == "GRANDE":
            subtotalrefresco=numero*60

        self.subtotalDulceria=self.subtotalDulceria+subtotalrefresco
        self.lbSubtotal.SetLabel(f"{self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria+"\n" + f"{numero}     Refresco:  {sabor}  tamaño  {tamanyo}\n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def limpiarD(self):
        #Limpiamos las variables de instancia
        self.subtotalDulceria=0
        self.infoDulceria=""

        #Limpiamos los controles
        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("---")
        self.lbSubtotal.SetLabel("$00.00")

    def limpiarDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        self.limpiarD()
        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: Ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
            "Confirmación de Dulcería.\n"
            f"¿Está seguro que desea adquirir??\n\n{self.infoDulceria}\n"
            f"Subtotal Dulceria: ${self.subtotalDulceria}",
            "Dulcería",style=wx.YES_NO | wx.ICON_QUESTION)

        respuesta = pregunta.ShowModal()
        pregunta.Destroy()   # Cerramos el diálogo

        if respuesta == wx.ID_YES:
            v4 = Ventana4(self, 
                          informacion=self.infoTaquilla,
                          subtotal1=self.subtotalTaquilla, 
                          informacion2=self.infoDulceria, 
                          subtotal2=self.subtotalDulceria)

            v4.Show()
            self.limpiarD()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarD()
        event.Skip()

# end of class Ventana3
class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((735, 726))
        self.SetTitle("Taquilla")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("./logo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(5, 234, 207))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("taquilla.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("taquilla.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_3, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Película:")
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_4.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_4, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["IT", "La Hermanastra", "Superman"], style=wx.CB_DROPDOWN)
        self.cmbPelicula.SetMinSize((120, 30))
        self.cmbPelicula.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_4.Add(self.cmbPelicula, 0, 0, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        self.lbSala.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(self.lbSala, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario1.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_5.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario2.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_5.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        self.rbHorario3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_5.Add(self.rbHorario3, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("pelicula1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.bmPelicula, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_6.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_6, 0, wx.EXPAND, 0)

        grid_sizer_6 = wx.GridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos ($80):")
        label_7.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(label_7, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        self.tfAdultos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_6.Add(self.tfAdultos, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores ($70):")
        label_8.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(label_8, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        self.tfMenores.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_6.Add(self.tfMenores, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        self.lbSubtotal.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((170, 54))
        self.btnLimpiar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnLimpiar.SetBitmap(wx.Bitmap("limpiar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnLimpiar, 0, 0, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente ")
        self.btnSiguiente.SetMinSize((170, 54))
        self.btnSiguiente.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnSiguiente.SetBitmap(wx.Bitmap("siguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnSiguiente, 0, wx.ALIGN_RIGHT, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self,ruta):
        print(f"Imagen a cargar: {ruta}")
        bitmap =wx.Bitmap(ruta, wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)
        
    def seleccionPelicula(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""
        
        print(f"Pelicula seleccionada: {pelicula}")
        
        if pelicula == "IT":
            imagen="pelicula1.png"
            sala="1"
            horario1="14:00"
            horario2="17:00"
            horario3="20:00"

        elif pelicula == "La Hermanastra":
            imagen="pelicula2.png"
            sala="2"
            horario1="13:30"
            horario2="16:30"
            horario3="19:30"

        elif pelicula == "Superman":
            imagen="pelicula3.png"
            sala="3"
            horario1="15:00"
            horario2="18:00"
            horario3="21:00"
        
        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"Pelicula: {pelicula}  \n  Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    
        

    def seleccionHorario1(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.adultos = int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal=subtotal_a 
            self.lbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal=(self.adultos*80) + subtotal_b 
            self.lbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    #Creacion de la función limpiar para la Ventana 2   
    def limpiarValores_Campos(self):

        #Limpiar Variables de Instancia
        self.subtotal=0
        self.adultos=0
        self.menores=0
        self.informacion=""
        self.horarioSeleccionado=""

        #Limpiar Campos
        self.cargar_imagen("logo.png")
        self.rbHorario1.SetLabel("00:00")
        self.rbHorario2.SetLabel("00:00")
        self.rbHorario3.SetLabel("00:00")
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.cmbPelicula.SetSelection(wx.NOT_FOUND)
        self.lbSala.SetLabel("---")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.lbSubtotal.SetLabel("0")
        


    def limpiarTaquilla(self, event):  # wxGlade: Ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.informacion = f"{self.informacion}  \n  Horario: {self.horarioSeleccionado}"
        self.informacion = f"{self.informacion}  \n  Adultos: {self.adultos}\n  Menores de 12 años: {self.menores}"
        self.informacion = f"{self.informacion}  \n  Subtotal: {self.subtotal}"
        
        pregunta = wx.MessageDialog(
        self,
        f"Confirmación de Taquilla.\n"
        f"¿Está seguro que desea adquirir?\n\n{self.informacion}",
        "Taquilla",
        style=wx.YES_NO | wx.ICON_QUESTION
        )
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()  # Cerramos el diálogo
        
        if respuesta == wx.ID_YES:
            print(f"Venta de Taquilla realizada\n {self.informacion}")
            v3 = Ventana3(self, informacion=self.informacion, subtotal=self.subtotal)
            v3.Show()
            self.limpiarValores_Campos()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()

        event.Skip()

# end of class Ventana2

class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((462, 441))
        self.SetTitle(u"Inicio de sesión - Cine Plus ")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("./logo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(104, 104, 104))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido(a) a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTitulo.SetMinSize((132, 35))
        lbTitulo.SetForegroundColour(wx.Colour(255, 255, 255))
        lbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbTitulo, 0, wx.EXPAND, 0)

        lbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("logo.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUsuario.SetMinSize((445, 20))
        lbUsuario.SetForegroundColour(wx.Colour(255, 255, 255))
        lbUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbUsuario, 0, wx.EXPAND, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetMinSize((445, 20))
        lbClave.SetForegroundColour(wx.Colour(255, 255, 255))
        lbClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbClave, 0, wx.EXPAND, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetBackgroundColour(wx.Colour(180, 219, 255))
        self.btnEntrar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetBackgroundColour(wx.Colour(255, 111, 128))
        self.btnSalir.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        nombre  = self.tfUsuario.GetValue ( )
        clave  = self.tfClave.GetValue ( )
        
        if nombre == "Pau" and clave == "123":
         print(f"¡Bienvenida, {nombre}! Acceso autorizado.")
         v2 = Ventana2(self)
         v2.Show()
         self.Hide() 
        else:
         print("Acceso denegado. Usuario o clave incorrectos.")
        
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        pregunta = wx.MessageDialog(self, "Se cerrará la ventana.\n" \
        "¿Está seguro que desea salir?","Confirmar salida",style=wx.YES_NO | wx.ICON_QUESTION)
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()  # Cerramos el diálogo
        
        if respuesta == wx.ID_YES:
            print("Bye!")
            self.Close()  # Cierra la ventana
        event.Skip()

# end of class Ventana1

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
